### ISSUE TITLE
Support configurable emote sizes

### ISSUE THREAD

**Issue by clifg** [clifg/MovieNight#2]
We should be able to have bigger emotes. At least gifs should be bigger

**Comment by samiringo** [comment]
This is pretty easy to do, we just hardcode the pixel size. Do we want everything to be the same size? I'm thinking gifs should be bigger than emojis, but maybe emojis should be bigger too. Could just try something and see how we feel about it.

**Comment by clifg** [comment]
@samiringo  🙏
